### ISSUE TITLE
npm ERR! `always-auth` is not a valid npm option

### ISSUE THREAD

**Issue by heunghingwan** [jenkinsci/npm-yarn-wrapper-steps-plugin#18]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
Jenkins: 2.375.3
OS: Linux - 5.14.0-162.12.1.el9_1.0.2.x86_64
Java: 11.0.18 - Red Hat, Inc. (OpenJDK 64-Bit Server VM)
---
ant:481.v7b_09e538fcca
antisamy-markup-formatter:155.v795fb_8702324
apache-httpcomponents-client-4-api:4.5.13-138.v4e7d9a_7b_a_e61
authentication-tokens:1.4
bootstrap4-api:4.6.0-5
bootstrap5-api:5.2.1-3
bouncycastle-api:2.27
branch-api:2.1071.v1a_188a_562481
build-timeout:1.28
caffeine-api:2.9.3-65.v6a_47d0f4d1fe
checks-api:1.8.1
cloudbees-folder:6.800.v71307ca_b_986b
command-launcher:90.v669d7ccb_7c31
commons-lang3-api:3.12.0-36.vd97de6465d5b_
commons-text-api:1.10.0-36.vc008c8fcda_7b_
credentials:1214.v1de940103927
credentials-binding:523.vd859a_4b_122e6
data-tables-api:1.12.1-4
display-url-api:2.3.7
docker-commons:1.21
docker-java-api:3.2.13-68.va_875df25a_b_45
docker-plugin:1.3.0
docker-workflow:563.vd5d2e5c4007f
durable-task:504.vb10d1ae5ba2f
echarts-api:5.4.0-1
email-ext:2.94
font-awesome-api:6.2.1-1
generic-webhook-trigger:1.86.2
git:5.0.0
git-client:4.1.0
git-parameter:0.9.18
git-server:99.va_0826a_b_cdfa_d
gitee:1.2.7
github:1.37.0
github-api:1.303-400.v35c2d8258028
github-branch-source:1701.v00cc8184df93
gradle:2.3
http_request:1.16
instance-identity:142.v04572ca_5b_265
ionicons-api:31.v4757b_6987003
jackson2-api:2.14.2-319.v37853346a_229
jakarta-activation-api:2.0.1-3
jakarta-mail-api:2.0.1-3
javax-activation-api:1.2.0-6
javax-mail-api:1.6.2-9
jaxb:2.3.8-1
jdk-tool:63.v62d2fd4b_4793
jjwt-api:0.11.5-77.v646c772fddb_0
jnr-posix-api:3.1.16-2
jquery:1.12.4-1
jquery3-api:3.6.1-2
jsch:0.1.55.61.va_e9ee26616e7
junit:1177.v90374a_ef4d09
ldap:659.v8ca_b_a_fe79fa_d
lockable-resources:1123.v4002ee23c671
mailer:448.v5b_97805e3767
matrix-auth:3.1.6
matrix-project:785.v06b_7f47b_c631
mina-sshd-api-common:2.9.2-50.va_0e1f42659a_a
mina-sshd-api-core:2.9.2-50.va_0e1f42659a_a
npm-yarn-wrapper-steps:0.4.0
okhttp-api:4.10.0-125.v3593b_a_f8c97b_
pam-auth:1.10
pipeline-build-step:2.18.1
pipeline-github-lib:38.v445716ea_edda_
pipeline-graph-analysis:202.va_d268e64deb_3
pipeline-groovy-lib:629.vb_5627b_ee2104
pipeline-input-step:466.v6d0a_5df34f81
pipeline-milestone-step:111.v449306f708b_7
pipeline-model-api:2.2118.v31fd5b_9944b_5
pipeline-model-definition:2.2118.v31fd5b_9944b_5
pipeline-model-extensions:2.2118.v31fd5b_9944b_5
pipeline-rest-api:2.31
pipeline-stage-step:305.ve96d0205c1c6
pipeline-stage-tags-metadata:2.2118.v31fd5b_9944b_5
pipeline-stage-view:2.31
pipeline-utility-steps:2.15.1
plain-credentials:143.v1b_df8b_d3b_e48
plugin-util-api:2.20.0
popper-api:1.16.1-3
popper2-api:2.11.6-2
qy-wechat-notification:1.1.3
resource-disposer:0.21
scm-api:631.v9143df5b_e4a_a
script-security:1229.v4880b_b_e905a_6
snakeyaml-api:1.33-95.va_b_a_e3e47b_fa_4
ssh-agent:295.v9ca_a_1c7cc3a_a_
ssh-credentials:305.v8f4381501156
ssh-slaves:2.854.v7fd446b_337c9
sshd:3.275.v9e17c10f2571
structs:324.va_f5d6774f3a_d
timestamper:1.22
token-macro:321.vd7cc1f2a_52c8
trilead-api:2.84.v72119de229b_7
variant:59.vf075fe829ccb
workflow-aggregator:590.v6a_d052e5a_a_b_5
workflow-api:1208.v0cc7c6e0da_9e
workflow-basic-steps:1010.vf7a_b_98e847c1
workflow-cps:3618.v13db_a_21f0fcf
workflow-durable-task-step:1234.v019404b_3832a
workflow-job:1268.v6eb_e2ee1a_85a
workflow-multibranch:733.v109046189126
workflow-scm-step:400.v6b_89a_1317c9a_
workflow-step-api:639.v6eca_cd8c04a_a_
workflow-support:839.v35e2736cfd5c
ws-cleanup:0.44

  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Debian 11.6

### Reproduction steps

1. set node LTS version with .nvmrc file
2. start build

### Expected Results

build with no error

### Actual Results

```
16:22:53  [Pipeline] {
16:22:53  [Pipeline] withNPMWrapper
16:22:54  Found '/data/jenkins/workspace/<deleted>/.nvmrc' with version <lts/*>
16:22:55  v18.14.2 is already installed.
16:22:56  Now using node v18.14.2 (npm v9.5.0)
16:22:57  npm ERR! `always-auth` is not a valid npm option
16:22:57  
16:22:57  npm ERR! A complete log of this run can be found in:
16:22:57  npm ERR!     /home/jenkins/.npm/_logs/2023-03-02T08_22_56_961Z-debug-0.log
16:22:57  [Pipeline] // withNPMWrapper
16:22:58  [Pipeline] }
```

### Anything else?

npm log
```
0 verbose cli /home/jenkins/.nvm/versions/node/v18.14.2/bin/node /home/jenkins/.nvm/versions/node/v18.14.2/bin/npm
1 info using npm@9.5.0
2 info using node@v18.14.2
3 timing npm:load:whichnode Completed in 3ms
4 timing config:load:defaults Completed in 3ms
5 timing config:load:file:/home/jenkins/.nvm/versions/node/v18.14.2/lib/node_modules/npm/npmrc Completed in 0ms
6 timing config:load:builtin Completed in 1ms
7 timing config:load:cli Completed in 2ms
8 timing config:load:env Completed in 1ms
9 timing config:load:file:/data/jenkins/workspace/<deleted>/.npmrc Completed in 1ms
10 timing config:load:project Completed in 3ms
11 timing config:load:file:/data/jenkins/workspace/<deleted>@tmp/.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:/home/jenkins/.nvm/versions/node/v18.14.2/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 1ms
15 timing config:load:setEnvs Completed in 1ms
16 timing config:load Completed in 12ms
17 timing npm:load:configload Completed in 12ms
18 timing npm:load:mkdirpcache Completed in 0ms
19 timing npm:load:mkdirplogs Completed in 1ms
20 verbose title npm config set always-auth true
21 verbose argv "config" "set" "always-auth" "true"
22 timing npm:load:setTitle Completed in 2ms
23 timing config:load:flatten Completed in 5ms
24 timing npm:load:display Completed in 6ms
25 verbose logfile logs-max:10 dir:/home/jenkins/.npm/_logs/2023-03-02T08_22_56_961Z-
26 verbose logfile /home/jenkins/.npm/_logs/2023-03-02T08_22_56_961Z-debug-0.log
27 timing npm:load:logFile Completed in 8ms
28 timing npm:load:timers Completed in 0ms
29 timing npm:load:configScope Completed in 0ms
30 timing npm:load Completed in 34ms
31 info config set "always-auth" "true"
32 timing command:config Completed in 2ms
33 verbose stack Error: `always-auth` is not a valid npm option
33 verbose stack     at Config.set (/home/jenkins/.nvm/versions/node/v18.14.2/lib/node_modules/npm/lib/commands/config.js:158:15)
33 verbose stack     at Config.exec (/home/jenkins/.nvm/versions/node/v18.14.2/lib/node_modules/npm/lib/commands/config.js:120:22)
33 verbose stack     at Config.cmdExec (/home/jenkins/.nvm/versions/node/v18.14.2/lib/node_modules/npm/lib/base-command.js:130:17)
33 verbose stack     at Npm.exec (/home/jenkins/.nvm/versions/node/v18.14.2/lib/node_modules/npm/lib/npm.js:154:20)
33 verbose stack     at async module.exports (/home/jenkins/.nvm/versions/node/v18.14.2/lib/node_modules/npm/lib/cli.js:134:5)
34 verbose cwd /data/jenkins/workspace/<deleted>
35 verbose Linux 5.10.0-21-amd64
36 verbose node v18.14.2
37 verbose npm  v9.5.0
38 error `always-auth` is not a valid npm option
39 verbose exit 1
40 timing npm Completed in 56ms
41 verbose code 1
42 error A complete log of this run can be found in:
42 error     /home/jenkins/.npm/_logs/2023-03-02T08_22_56_961Z-debug-0.log

```

**Comment by qalinn** [comment]
I have the same issue.

**Comment by heunghingwan** [comment]
Find something related: https://github.com/aws/aws-cli/pull/7468
Adding a try catch here should fix it:
https://github.com/jenkinsci/npm-yarn-wrapper-steps-plugin/blob/e7b03fd9ffffa112f9aa0183762e75e7bd736f36/src/main/java/io/interrogate/npmyarnwrappersteps/plugin/NPMBuildWrapper.java#L117-L118
